title: XJZProxy
downloads_url: https://github.com/xiejiangzhi/xjzproxy-docs/releases
feedback_url: https://github.com/xiejiangzhi/xjzproxy-docs/issues
google_analytics: UA-140346671-1

theme: jekyll-theme-cayman
