project:
  host: xjz.pw

partials:
  user:
    id: .t/integer
    nickname: string len 10

responses:
  invalid_page:
    http_code: 400
    data:
      code: 1
      msg: Invalid page

  list_users:
    http_code: 400
    headers:
      content_type: application/json
    data:
      items: .p/user * 2
      total: 2

apis:
  - title: Get all users
    desc: more desc of this API
    method: GET
    path: /api/v1/users
    labels: ['auth']
    query:
      page: .t/integer
    response:
      success: .r/list_users
      error: .r/invalid_page
      json:
        headers:
          content_type: application/json
        data:
          a: 1

      str:
        headers:
          content_type: text/plain
        data: str

